spring:
  datasource:
    url: jdbc:postgresql://${database_host}:5432/${database_name}
    username: ${database_username}
    password: ${database_password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
      mode: always